name: Build

on:
    workflow_call:
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                version: [v16.14.2, v17.9.0]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.x'
                  architecture: 'x64'
            - name: Set up tools
              run: sudo apt install -y build-essential
            - uses: nttld/setup-ndk@v1
              id: setup-ndk
              with:
                  ndk-version: r23b
            - name: Set up NodeJS
              run: |
                  curl -O https://nodejs.org/dist/${{ matrix.version }}/node-${{ matrix.version }}.tar.gz
                  tar -zxf ./node-${{ matrix.version }}.tar.gz -C ./
                  mv node-${{ matrix.version }} node
                  rm ./node-${{ matrix.version }}.tar.gz
            - name: Patch files
              env:
                  NODE_VERSION: ${{ matrix.version }}
              run: |
                  chmod +x ./scripts/patch.sh
                  ./scripts/patch.sh
            - uses: actions/cache@v3
              with:
                  path: ./node/out
                  key: node-out-android-${{ matrix.version }}-arm64
            - name: Build NodeJS
              env:
                  NDK_PATH: ${{ steps.setup-ndk.outputs.ndk-path }}
              run: |
                  chmod +x ./scripts/build.sh
                  ./scripts/build.sh
            - uses: benjlevesque/short-sha@v1.2
              id: short-sha
              with:
                  length: 7
            - uses: actions/upload-artifact@v3
              with:
                  name: libnode-${{ matrix.version }}-${{ steps.short-sha.outputs.sha }}-android-arm64
                  path: ./build
                  retention-days: 1
